Fix build errors
Fixes the following build errors:
- src/pages/NotificationCenter.tsx(454,32): error TS2304: Cannot find name 'Edit'.
- src/pages/SuperAdminDashboard.tsx(443,83): error TS2551: Property 'getUserByEmail' does not exist on type 'GoTrueAdminApi'. Did you mean 'getUserById'?
- src/pages/UserManagement.tsx(773,24): error TS2304: Cannot find name 'Mail'.